# Database to benchmark
database=memgraph

# -------------------------
# Neo4j
# -------------------------
neo4j.uri=bolt+s://db-370b12e9.databases.cognodb.com
neo4j.username=cognodb
neo4j.password=3c3183582dfdd3adb24ca472c8ac4fbc

# -------------------------
# Memgraph
# -------------------------
memgraph.uri=bolt://localhost:7687
memgraph.username=
memgraph.password=

# -------------------------
# FalkorDB
# -------------------------
falkordb.host=localhost
falkordb.port=6379
falkordb.username=
falkordb.password=

# -------------------------
# ArangoDB
# -------------------------
arangodb.host=localhost
arangodb.port=8529
arangodb.database=_system
arangodb.username=root
arangodb.password=